; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico_bootsel

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
upload_protocol = picotool
upload_port = /dev/ttyACM0
board_upload.use_1200bps_touch = no
board_upload.wait_for_upload_port = no
monitor_port = /dev/ttyACM0
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1
lib_deps =
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1
    etherkit/Etherkit Si5351@^2.2.0

[env:pico_bootsel]
extends = env:pico
upload_protocol = custom
upload_command = python3 $PROJECT_DIR/scripts/upload_uf2.py $PROJECT_BUILD_DIR/$PIOENV/firmware.uf2
